import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const clientRoot = join(root, 'src', 'client', 'app')
const outputPath = join(
  root,
  'src',
  'server',
  'static-client-assets.generated.ts'
)
const checkOnly = process.argv.includes('--check')

const bundleClient = async () => {
  const result = await build({
    entryPoints: [join(clientRoot, 'app.ts')],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    sourcemap: false,
    logLevel: 'silent',
    legalComments: 'none'
  })

  const output = result.outputFiles[0]
  if (!output) {
    throw new Error('esbuild did not produce a client JavaScript bundle')
  }

  return output.text
}

const assets = [
  {
    pathname: '/',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/index.html',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/styles.css',
    source: 'styles.css',
    exportName: 'CLIENT_CSS',
    contentType: 'text/css; charset=utf-8'
  },
  {
    pathname: '/client.js',
    inlineBody: 'import "/client/app/app.js";\n',
    exportName: 'CLIENT_JS_COMPAT',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/client/app/app.js',
    inlineBody: await bundleClient(),
    exportName: 'CLIENT_APP_JS',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/manifest.webmanifest',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/site.webmanifest',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/manifest.json',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/icon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/favicon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/icon-maskable.svg',
    source: 'icon-maskable.svg',
    exportName: 'CLIENT_MASKABLE_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/favicon.ico',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/apple-touch-icon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/sw.js',
    source: 'sw.js',
    exportName: 'CLIENT_SW',
    contentType: 'text/javascript; charset=utf-8'
  }
]

const uniqueSources = new Map()
for (const asset of assets) {
  if (!uniqueSources.has(asset.exportName)) {
    uniqueSources.set(asset.exportName, {
      source: asset.source,
      inlineBody: asset.inlineBody
    })
  }
}

const extractModuleImports = (body) => {
  const imports = new Set()
  const importPattern =
    /\bimport\s+(?:[^'"]*?\s+from\s+)?['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)/g

  for (const match of body.matchAll(importPattern)) {
    imports.add(match[1] ?? match[2])
  }

  return [...imports]
}

const resolveModulePath = (fromPathname, specifier) => {
  if (
    !specifier.startsWith('./') &&
    !specifier.startsWith('../') &&
    !specifier.startsWith('/')
  ) {
    throw new Error(`${fromPathname} imports non-runtime module ${specifier}`)
  }

  return new URL(specifier, `https://cepheus.test${fromPathname}`).pathname
}

const lines = [
  '// Generated by scripts/build-client.mjs. Do not edit by hand.',
  ''
]
const sourceBodies = new Map()

for (const [exportName, { source, inlineBody }] of uniqueSources) {
  const body = inlineBody ?? (await readFile(join(clientRoot, source), 'utf8'))
  sourceBodies.set(exportName, body)
}

const buildHash = createHash('sha256')
for (const body of sourceBodies.values()) {
  buildHash.update(body)
}
const shortHash = buildHash.digest('hex').slice(0, 12)

for (const [exportName, rawBody] of sourceBodies) {
  const body = rawBody.replaceAll('__BUILD_HASH__', shortHash)
  lines.push(`export const ${exportName} = ${JSON.stringify(body)}`)
}

const servedPathnames = new Set(assets.map((asset) => asset.pathname))
const javascriptAssets = assets.filter((asset) =>
  asset.contentType.startsWith('text/javascript')
)

for (const asset of javascriptAssets) {
  const body = sourceBodies.get(asset.exportName)
  if (body === undefined) {
    throw new Error(`${asset.pathname} has no generated body`)
  }

  for (const specifier of extractModuleImports(body)) {
    const importedPathname = resolveModulePath(asset.pathname, specifier)
    if (!servedPathnames.has(importedPathname)) {
      throw new Error(
        `${asset.pathname} imports unserved runtime module ${importedPathname}`
      )
    }
  }
}

lines.push(
  '',
  'export const STATIC_CLIENT_ASSETS = {',
  ...assets.map(
    (asset) =>
      `  ${JSON.stringify(asset.pathname)}: {body: ${asset.exportName}, contentType: ${JSON.stringify(asset.contentType)}},`
  ),
  '} as const',
  ''
)

const output = lines.join('\n')

if (checkOnly) {
  let currentOutput = ''
  try {
    currentOutput = await readFile(outputPath, 'utf8')
  } catch {
    console.error(`${outputPath} is missing. Run npm run build:client.`)
    process.exit(1)
  }

  if (currentOutput !== output) {
    console.error(`${outputPath} is stale. Run npm run build:client.`)
    process.exit(1)
  }

  console.log('Generated client asset is fresh.')
} else {
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output)
}
