import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const clientRoot = join(root, 'src', 'client', 'app')
const compiledClientRoot = join(root, '.tmp', 'client')
const outputPath = join(
  root,
  'src',
  'server',
  'static-client-assets.generated.ts'
)

const assets = [
  {
    pathname: '/',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/index.html',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/styles.css',
    source: 'styles.css',
    exportName: 'CLIENT_CSS',
    contentType: 'text/css; charset=utf-8'
  },
  {
    pathname: '/client.js',
    inlineBody: 'import "/client/app/app.js";\n',
    exportName: 'CLIENT_JS_COMPAT',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/client/app/app.js',
    source: join(compiledClientRoot, 'app', 'app.js'),
    exportName: 'CLIENT_APP_JS',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/client/dice.js',
    source: join(compiledClientRoot, 'dice.js'),
    exportName: 'CLIENT_DICE_JS',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/manifest.webmanifest',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/site.webmanifest',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/manifest.json',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/icon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/favicon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/icon-maskable.svg',
    source: 'icon-maskable.svg',
    exportName: 'CLIENT_MASKABLE_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/favicon.ico',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/apple-touch-icon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/sw.js',
    source: 'sw.js',
    exportName: 'CLIENT_SW',
    contentType: 'text/javascript; charset=utf-8'
  }
]

const uniqueSources = new Map()
for (const asset of assets) {
  if (!uniqueSources.has(asset.exportName)) {
    uniqueSources.set(asset.exportName, {
      source: asset.source,
      inlineBody: asset.inlineBody
    })
  }
}

await rm(compiledClientRoot, { recursive: true, force: true })
execFileSync('npx', ['tsc', '-p', 'tsconfig.client.json'], {
  cwd: root,
  stdio: 'inherit'
})

const lines = [
  '// Generated by scripts/build-client.mjs. Do not edit by hand.',
  ''
]
const sourceBodies = new Map()

for (const [exportName, { source, inlineBody }] of uniqueSources) {
  const body =
    inlineBody ??
    (await readFile(
      typeof source === 'string' && source.startsWith(root)
        ? source
        : join(clientRoot, source),
      'utf8'
    ))
  sourceBodies.set(exportName, body)
}

const buildHash = createHash('sha256')
for (const body of sourceBodies.values()) {
  buildHash.update(body)
}
const shortHash = buildHash.digest('hex').slice(0, 12)

for (const [exportName, rawBody] of sourceBodies) {
  const body = rawBody.replaceAll('__BUILD_HASH__', shortHash)
  lines.push(`export const ${exportName} = ${JSON.stringify(body)}`)
}

lines.push(
  '',
  'export const STATIC_CLIENT_ASSETS = {',
  ...assets.map(
    (asset) =>
      `  ${JSON.stringify(asset.pathname)}: {body: ${asset.exportName}, contentType: ${JSON.stringify(asset.contentType)}},`
  ),
  '} as const',
  ''
)

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, lines.join('\n'))
