import {mkdir, readFile, writeFile} from 'node:fs/promises'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const clientRoot = join(root, 'src', 'client', 'app')
const outputPath = join(
  root,
  'src',
  'server',
  'static-client-assets.generated.ts'
)

const assets = [
  {
    pathname: '/',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/index.html',
    source: 'index.html',
    exportName: 'CLIENT_HTML',
    contentType: 'text/html; charset=utf-8'
  },
  {
    pathname: '/styles.css',
    source: 'styles.css',
    exportName: 'CLIENT_CSS',
    contentType: 'text/css; charset=utf-8'
  },
  {
    pathname: '/client.js',
    source: 'app.ts',
    exportName: 'CLIENT_JS',
    contentType: 'text/javascript; charset=utf-8'
  },
  {
    pathname: '/manifest.webmanifest',
    source: 'manifest.webmanifest',
    exportName: 'CLIENT_MANIFEST',
    contentType: 'application/manifest+json'
  },
  {
    pathname: '/icon.svg',
    source: 'icon.svg',
    exportName: 'CLIENT_ICON',
    contentType: 'image/svg+xml'
  },
  {
    pathname: '/sw.js',
    source: 'sw.js',
    exportName: 'CLIENT_SW',
    contentType: 'text/javascript; charset=utf-8'
  }
]

const uniqueSources = new Map()
for (const asset of assets) {
  if (!uniqueSources.has(asset.exportName)) {
    uniqueSources.set(asset.exportName, asset.source)
  }
}

const lines = [
  '// Generated by scripts/build-client.mjs. Do not edit by hand.',
  ''
]

for (const [exportName, source] of uniqueSources) {
  const body = await readFile(join(clientRoot, source), 'utf8')
  lines.push(`export const ${exportName} = ${JSON.stringify(body)}`)
}

lines.push(
  '',
  'export const STATIC_CLIENT_ASSETS = {',
  ...assets.map(
    (asset) =>
      `  ${JSON.stringify(asset.pathname)}: {body: ${asset.exportName}, contentType: ${JSON.stringify(asset.contentType)}},`
  ),
  '} as const',
  ''
)

await mkdir(dirname(outputPath), {recursive: true})
await writeFile(outputPath, lines.join('\n'))
