import * as assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import type { GeneratedCharacterSummary } from './character-command-plan'
import {
  deriveGeneratedCharacterOutcomeLabels,
  deriveGeneratedCharacterPreview,
  deriveGeneratedCharacterPreviewChips,
  deriveGeneratedCharacterPreviewLines,
  formatGeneratedCharacterCharacteristics
} from './character-generator-preview'

const generatedCharacter = (
  overrides: Partial<GeneratedCharacterSummary> = {}
): GeneratedCharacterSummary => ({
  name: 'Iona Vesh',
  career: 'Scout',
  age: 22,
  characteristics: {
    str: 7,
    dex: 8,
    end: 6,
    int: 9,
    edu: 10,
    soc: 5
  },
  skills: ['Pilot-1', 'Vacc Suit-0'],
  credits: 4000,
  notes: 'Generated by test.',
  qualificationRoll: 8,
  survivalRoll: 9,
  survivalPassed: true,
  commissionRoll: null,
  commissionPassed: null,
  advancementRoll: 7,
  advancementPassed: true,
  drafted: false,
  creationOutcome: {
    survivalPassed: true,
    canCommission: false,
    commissionPassed: null,
    canAdvance: true,
    advancementPassed: true
  },
  ...overrides
})

describe('character generator preview helpers', () => {
  it('formats characteristics in Cepheus order', () => {
    assert.equal(
      formatGeneratedCharacterCharacteristics({
        str: 7,
        dex: 8,
        end: 6,
        int: 9,
        edu: 10,
        soc: 5
      }),
      'STR 7  DEX 8  END 6  INT 9  EDU 10  SOC 5'
    )
  })

  it('derives outcome labels with visible roll results', () => {
    assert.deepEqual(
      deriveGeneratedCharacterOutcomeLabels(generatedCharacter()),
      {
        qualification: 'Qualified (8)',
        survival: 'Survived (9)',
        commission: null,
        advancement: 'Advanced (7)',
        credits: '4000 credits'
      }
    )

    assert.deepEqual(
      deriveGeneratedCharacterOutcomeLabels(
        generatedCharacter({
          qualificationRoll: 5,
          survivalRoll: 4,
          survivalPassed: false,
          commissionRoll: 6,
          commissionPassed: false,
          advancementRoll: null,
          advancementPassed: null,
          drafted: true,
          creationOutcome: {
            survivalPassed: false,
            canCommission: true,
            commissionPassed: false,
            canAdvance: false,
            advancementPassed: null
          }
        })
      ),
      {
        qualification: 'Drafted (5)',
        survival: 'Mishap (4)',
        commission: 'No commission (6)',
        advancement: null,
        credits: '4000 credits'
      }
    )
  })

  it('derives preview lines for the Roll and Accept UI', () => {
    assert.deepEqual(
      deriveGeneratedCharacterPreviewLines(generatedCharacter()),
      [
        {
          key: 'characteristics',
          label: 'Characteristics',
          value: 'STR 7  DEX 8  END 6  INT 9  EDU 10  SOC 5'
        },
        {
          key: 'skills',
          label: 'Skills',
          value: 'Pilot-1, Vacc Suit-0'
        }
      ]
    )

    assert.deepEqual(
      deriveGeneratedCharacterPreviewLines(generatedCharacter({ skills: [] })),
      [
        {
          key: 'characteristics',
          label: 'Characteristics',
          value: 'STR 7  DEX 8  END 6  INT 9  EDU 10  SOC 5'
        },
        {
          key: 'skills',
          label: 'Skills',
          value: '-'
        }
      ]
    )
  })

  it('derives ordered outcome chips with tone hints', () => {
    assert.deepEqual(
      deriveGeneratedCharacterPreviewChips(generatedCharacter()),
      [
        { key: 'survival', label: 'Survived (9)', tone: 'success' },
        { key: 'credits', label: '4000 credits', tone: 'neutral' },
        { key: 'qualification', label: 'Qualified (8)', tone: 'success' },
        { key: 'advancement', label: 'Advanced (7)', tone: 'success' }
      ]
    )

    assert.deepEqual(
      deriveGeneratedCharacterPreviewChips(
        generatedCharacter({
          qualificationRoll: 5,
          survivalRoll: 4,
          survivalPassed: false,
          commissionRoll: 6,
          commissionPassed: false,
          advancementRoll: null,
          advancementPassed: null,
          drafted: true
        })
      ),
      [
        { key: 'survival', label: 'Mishap (4)', tone: 'warning' },
        { key: 'credits', label: '4000 credits', tone: 'neutral' },
        { key: 'qualification', label: 'Drafted (5)', tone: 'warning' },
        { key: 'commission', label: 'No commission (6)', tone: 'neutral' }
      ]
    )
  })

  it('derives a complete nullable preview view model', () => {
    assert.equal(deriveGeneratedCharacterPreview(null), null)
    assert.deepEqual(deriveGeneratedCharacterPreview(generatedCharacter()), {
      title: 'Iona Vesh',
      subtitle: 'Scout / Age 22',
      canAccept: true,
      lines: [
        {
          key: 'characteristics',
          label: 'Characteristics',
          value: 'STR 7  DEX 8  END 6  INT 9  EDU 10  SOC 5'
        },
        {
          key: 'skills',
          label: 'Skills',
          value: 'Pilot-1, Vacc Suit-0'
        }
      ],
      chips: [
        { key: 'survival', label: 'Survived (9)', tone: 'success' },
        { key: 'credits', label: '4000 credits', tone: 'neutral' },
        { key: 'qualification', label: 'Qualified (8)', tone: 'success' },
        { key: 'advancement', label: 'Advanced (7)', tone: 'success' }
      ]
    })
  })
})
